name: Deploy to IONOS Hosting

on:
  push:
    branches:
      - main
      - master

jobs:
  sftp-deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: appleboy/scp-action@v0.1.4  # Acción correcta y existente
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/htdocs" # Probable ruta correcta para IONOS
          debug: true